### ISSUE TITLE
Update webRTC framework & AppRTCMobile code

### ISSUE THREAD

**Issue by LorenzoMcMaster** [crossle/AppRTCMobile#2]
It would be very useful to document the procedure to update the webRTC framework for this Xcode project. it's not using cocoaPods so I'm not sure how to do it.

For the appRTCMobile code, it can easily done manually but to have an official procedure would be also useful.

**Comment by Laurentfth** [comment]
Yes, update of webrtc framework would be very useful. I've tried but the code get broken.

**Comment by crossle** [comment]
plz wait a moment, updating

**Comment by Laurentfth** [comment]
thank you very much. I'm a beginner and I've been trying for hours without success.

**Comment by richardSevin** [comment]
I have tried to integrate https://webrtc.googlesource.com/src/+/master/examples/objc/AppRTCMobile/
inside an Xcode project but I still have issues.

I would be interested to see that project updated, since it's looking similar to what I'm trying to achieve.

thanks

**Comment by crossle** [comment]
Updated

**Comment by Laurentfth** [comment]
Thanks, I could build and install the App. It's great.
One thing that I don't understand is why your webrtc.framework is different from the one on google webrtc cocoapods. It's based on the same build 1.1.21820 but the headers are different.
It may look like a beginner question, but if you build the framework yourself, on the same source code version, it should produce the same result as cocoapods build. right?

**Comment by crossle** [comment]
Which different? the webrtc.framework  i compile myself

**Comment by Laurentfth** [comment]
In the cocoapods webrtc framework (https://cocoapods.org/pods/GoogleWebRTC) there is 4 headers missing compared to the webrtc framework in your project:
RTCCallbackLogger.h
RTCDtmfSender.h
RTCFileVideoCapturer.h
RTCPeerConnectionFactoryOptions.h
I think it's the official cocoapods version witch is broken because the missing headers are referenced by the WebRTC.h headed but are missing from the framework.
The problem is present in build 1.1.21820 and was also present in builds from last month. I guess other users trouble with cocoapods is the same as mine.

**Comment by Laurentfth** [comment]
After taking the 4 missing files from your webrtc framework and putting them inside the official one, I can build the app and it works fine on my iPhone.
So the issue is really in the official build.
